# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculadora_pb2 as calculadora__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calculadora_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculadoraStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Suma = channel.unary_unary(
                '/Calculadora/Suma',
                request_serializer=calculadora__pb2.Operacion.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                _registered_method=True)
        self.Resta = channel.unary_unary(
                '/Calculadora/Resta',
                request_serializer=calculadora__pb2.Operacion.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                _registered_method=True)
        self.Multiplicacion = channel.unary_unary(
                '/Calculadora/Multiplicacion',
                request_serializer=calculadora__pb2.Operacion.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                _registered_method=True)
        self.Division = channel.unary_unary(
                '/Calculadora/Division',
                request_serializer=calculadora__pb2.Operacion.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                _registered_method=True)


class CalculadoraServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Suma(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiplicacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Division(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculadoraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Suma': grpc.unary_unary_rpc_method_handler(
                    servicer.Suma,
                    request_deserializer=calculadora__pb2.Operacion.FromString,
                    response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            'Resta': grpc.unary_unary_rpc_method_handler(
                    servicer.Resta,
                    request_deserializer=calculadora__pb2.Operacion.FromString,
                    response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            'Multiplicacion': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiplicacion,
                    request_deserializer=calculadora__pb2.Operacion.FromString,
                    response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            'Division': grpc.unary_unary_rpc_method_handler(
                    servicer.Division,
                    request_deserializer=calculadora__pb2.Operacion.FromString,
                    response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Calculadora', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Calculadora', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Calculadora(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Suma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculadora/Suma',
            calculadora__pb2.Operacion.SerializeToString,
            calculadora__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculadora/Resta',
            calculadora__pb2.Operacion.SerializeToString,
            calculadora__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Multiplicacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculadora/Multiplicacion',
            calculadora__pb2.Operacion.SerializeToString,
            calculadora__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Division(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculadora/Division',
            calculadora__pb2.Operacion.SerializeToString,
            calculadora__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
